------------------------------------
Lexeme      Token       Line
------------------------------------
<CONSTANTES>: Constantes   [1]
<IDENT>: c   [1]
<OP_ASIG>: :=   [1]
<CTE_ENTERA>: 10   [1]
<PUNTO_COMA>: ;   [1]
<VARIABLES>: Variables   [2]
<IDENT>: alfa   [2]
<COMA>: ,   [2]
<IDENT>: beta   [2]
<PUNTOS_DOBLES>: :   [2]
<TIPO>: Alfabetico   [2]
<PUNTO_COMA>: ;   [2]
<PROTOTIPOS>: Prototipos   [3]
<FIN>: Fin   [5]
<DE>: de   [5]
<PROTOTIPOS>: Prototipos   [5]
<PUNTO_COMA>: ;   [5]
<PROGRAMA>: Programa   [7]
<IMPRIMENL>: Imprimenl   [8]
<PAREN_EMPIEZA>: (   [8]
<CTE_ALFA>: "hello world!"   [8]
<PAREN_TERMINA>: )   [8]
<PUNTO_COMA>: ;   [8]
<FIN>: Fin   [10]
<DE>: de   [10]
<PROGRAMA>: programa   [10]
<PUNTO>: .   [10]
